### ISSUE TITLE
Layout Discussion

### ISSUE THREAD

**Issue by Rerouter** [eez-open/CF-DIC#1]
For the dual inductor section, it seems like you would have a shorter routing by rotating both transformers, was there a reason behind the current orientation?

Equally it appears the diode / capacitor for both inductors could be placed on a far shorter loop.

I have to admit at this point Its hard for me to visualize all the current loops for this converter, just working on your footnote to keep the trace lengths even and as close as possible. 
![inductor](https://user-images.githubusercontent.com/15925855/45586042-3779cd00-b933-11e8-89d9-5df233da5e22.PNG)

**Comment by prasimix** [comment]
You're right. Rotating power inductors make sense, indeed. I'll try to rearrange that section and commit a new version soon.

**Comment by prasimix** [comment]
PCB layout is completely redesigned in r5B4 that works as intended, therefore this issue can be closed. Small corrections are included into the r5B5 version.
